name: SegmentAnalytics
description: Segment.com library for Flutter
version: 0.0.1
homepage: https://www.segment.com
author: FaisalAbid <faisal.abid@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: any

dev_dependencies:
  test: ^0.12.0
